version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  app:
    build: ./app
    env_file:
      - database.env
    restart: on-failure
    depends_on:
      - db
    links:
      - db
    ports:
      - "5000:5000"
  